name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # 4. Run tests
      - name: Run pytest
        run: pytest

      # 5. Run lint checks
      - name: Run flake8
        run: flake8 .

      # 6. Run type checks
      - name: Run mypy
        run: mypy .

      # 7. Run formatting check (black in --check mode)
      - name: Run black formatting check
        run: black --check .
