name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"   # match local version

      # === Cache HuggingFace + pip packages ===
      - name: Cache HuggingFace + pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/huggingface
            ~/.cache/torch
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt punkt_tab averaged_perceptron_tagger averaged_perceptron_tagger_eng stopwords wordnet omw-1.4

      # === Run tests ===
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest -v

      # === Lint check ===
      - name: Run flake8
        run: flake8 .
