name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest

      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt punkt_tab averaged_perceptron_tagger averaged_perceptron_tagger_eng stopwords wordnet omw-1.4

      # === Run tests ===
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest -v

      # === Autoformat with Black + isort ===
      - name: Autoformat with Black
        run: black .
      - name: Autoformat imports with isort
        run: isort .

      # === Commit formatting changes (if any) ===
      - name: Commit formatting changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "style: auto-format with black & isort"
            git push
          fi

      # === Lint check ===
      - name: Run flake8
        run: flake8 .